import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';

test('real atlas lookup, tree selection, transforms, export and atlas switching',async({page,baseURL})=>{
  const errors:string[]=[];const external:string[]=[];
  page.on('pageerror',e=>errors.push(e.message));
  const appOrigin=new URL(baseURL!).origin;
  page.on('request',r=>{if(r.url().startsWith('http')&&new URL(r.url()).origin!==appOrigin)external.push(r.url());});
  await page.goto('./');
  await expect(page.locator('.region-original')).toHaveText('Precentral_L');
  await expect(page.locator('.region-detail')).toContainText('52, 118, 122');
  await expect(page.locator('.canvas-loading')).toHaveCount(0);
  await expect(page.locator('.canvas-error')).toHaveCount(0);
  await expect(page.locator('.slice-status')).toHaveCount(0);
  await page.getByLabel('Search regions').fill('Thal_AV');
  await page.locator('[data-region="121"] .region-name').click();
  await expect(page.locator('.region-original')).toHaveText('Thal_AV_L');
  await page.getByLabel('Search regions').fill('');
  await page.getByRole('button',{name:'Talairach',exact:true}).click();
  await page.getByRole('button',{name:'Locate in brain'}).click();
  await expect(page.locator('.viewer-coordinate')).toContainText('Approximate transform');
  await page.getByRole('button',{name:'Voxel',exact:true}).click();
  await page.getByLabel('Coordinate X').fill('-1');
  await page.getByRole('button',{name:'Locate in brain'}).click();
  await expect(page.locator('.inline-error')).toContainText('Voxel indices must be integers');
  await page.getByRole('button',{name:'MNI',exact:true}).click();
  for(const [axis,value] of [['X','999'],['Y','999'],['Z','999']])await page.getByLabel(`Coordinate ${axis}`).fill(value);
  await page.getByRole('button',{name:'Locate in brain'}).click();
  await expect(page.locator('.empty-point')).toContainText('Outside the atlas volume');
  for(const [axis,value] of [['X','-38'],['Y','-8'],['Z','50']])await page.getByLabel(`Coordinate ${axis}`).fill(value);
  await page.getByRole('button',{name:'Locate in brain'}).click();
  await expect(page.locator('.region-original')).toHaveText('Precentral_L');
  await page.getByLabel('Allow approximate comparison between MNI templates').check();
  await expect(page.locator('.comparison-list')).not.toHaveClass(/updating/);
  await expect(page.locator('.comparison-card').first()).not.toContainText('Different reference template');
  await page.getByRole('button',{name:'Export',exact:true}).click();
  const downloadPromise=page.waitForEvent('download');
  await page.getByRole('button',{name:'Coordinate results · CSV'}).click();
  const d=await downloadPromise;expect(d.suggestedFilename()).toBe('BrainRosetta-coordinate.csv');
  const csv=await readFile((await d.path())!,'utf8');expect(csv).toContain('Precentral_L');expect(csv).toContain('MNIColin27');expect(csv).toContain('atlasHash');
  await page.getByLabel('Close dialog').click();
  await page.getByLabel('Atlas family').selectOption('Schaefer');
  await page.getByLabel('Atlas variant').selectOption('schaefer-1000-17Networks-2mm');
  await expect(page.locator('.workspace-toolbar')).toContainText('1000 regions');
  await expect(page.locator('.canvas-loading')).toHaveCount(0);
  await expect(page.locator('.canvas-error')).toHaveCount(0);
  await expect(page.locator('.slice-status')).toHaveCount(0);
  await page.getByRole('button',{name:'Show all',exact:true}).click();
  await expect(page.locator('.tree-footer')).toContainText('1000 selected');
  await page.screenshot({path:'/private/tmp/brainrosetta-schaefer.png'});
  await page.getByLabel('Atlas family').selectOption('Julich-Brain');
  await expect(page.locator('.workspace-toolbar')).toContainText('Julich-Brain 3.1');
  await expect(page.locator('.canvas-loading')).toHaveCount(0);
  await expect(page.locator('.canvas-error')).toHaveCount(0);
  await expect(page.locator('.region-original')).toBeVisible();
  await page.getByLabel('Allow approximate comparison between MNI templates').uncheck();
  await expect(page.locator('.empty-point')).toContainText('Different reference template');
  await expect(page.locator('.region-original')).toHaveCount(0);
  expect(errors).toEqual([]);expect(external).toEqual([]);
});

test('share URL restores state and narrow layout stays within viewport',async({page})=>{
  await page.goto('./');await expect(page.locator('.region-original')).toHaveText('Precentral_L');
  await page.getByLabel('Allow approximate comparison between MNI templates').check();
  await page.getByRole('button',{name:'Share view'}).click();
  await expect(page).toHaveURL(/#view=/);
  await page.reload();await expect(page.locator('.region-original')).toHaveText('Precentral_L');
  await expect(page.getByLabel('Allow approximate comparison between MNI templates')).toBeChecked();
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByLabel('Search regions')).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:'/private/tmp/brainrosetta-mobile.png',fullPage:true});
});

test('batch CSV is processed locally and downloaded',async({page})=>{
  await page.goto('./');await expect(page.locator('.region-detail')).toContainText('52, 118, 122');
  await page.getByRole('button',{name:'Import',exact:true}).click();
  const promise=page.waitForEvent('download');
  await page.locator('input[accept=".csv,.tsv,.txt"]').setInputFiles({name:'points.csv',mimeType:'text/csv',buffer:Buffer.from('x,y,z\n-38,-8,50\n999,999,999')});
  const d=await promise;expect(d.suggestedFilename()).toBe('BrainRosetta-batch.csv');
  const csv=await readFile((await d.path())!,'utf8');expect(csv).toContain('Precentral_L');expect(csv).toContain('outside');expect(csv).toContain('Different reference template');
  await expect(page.getByRole('status')).toContainText('2 coordinates');
});

test('slice and 3D clicks update the coordinate with their provenance',async({page})=>{
  await page.goto('./');await expect(page.locator('.region-original')).toHaveText('Precentral_L');
  await expect(page.locator('.slice-status')).toHaveCount(0);
  await expect(page.locator('.canvas-loading')).toHaveCount(0);
  const slice=page.getByLabel('Axial, coronal, and sagittal MRI slices');
  const box=(await slice.boundingBox())!;
  await slice.click({position:{x:box.width*.32,y:box.height*.48}});
  await page.getByRole('button',{name:'Export',exact:true}).click();
  const first=page.waitForEvent('download');await page.getByRole('button',{name:'Results & selected regions · JSON'}).click();
  const s=JSON.parse(await readFile((await (await first).path())!,'utf8'));expect(s.point.method).toBe('MRI slice voxel');
  await page.getByLabel('Close dialog').click();
  const brain=page.locator('.canvas-host canvas'),b=(await brain.boundingBox())!;
  await brain.click({position:{x:b.width*.5,y:b.height*.48}});
  await page.getByRole('button',{name:'Export',exact:true}).click();
  const second=page.waitForEvent('download');await page.getByRole('button',{name:'Results & selected regions · JSON'}).click();
  const t=JSON.parse(await readFile((await (await second).path())!,'utf8'));expect(t.point.method).toContain('3D mesh point');
});
