// citation.json is shared by the website and repository citation metadata.
import { readFileSync, writeFileSync } from 'node:fs';
const root=new URL('../',import.meta.url);
const c=JSON.parse(readFileSync(new URL('citation.json',root),'utf8'));
const q=JSON.stringify;
const cff=[
  '# Generated by node scripts/prepare_citation.mjs; edit citation.json.',
  'cff-version: 1.2.0', 'type: software',
  'message: "Please cite BrainRosetta and the original atlases used in your work. Record the build commit when using changes after the archived release."',
  `title: ${q(c.title)}`, 'authors:',
  ...c.authors.flatMap(a=>[`  - family-names: ${q(a['family-names'])}`,`    given-names: ${q(a['given-names'])}`,...(a.orcid?[`    orcid: ${q(a.orcid)}`]:[])]),
  ...['version','date-released','doi','repository-code','url','license'].map(k=>`${k}: ${q(c[k])}`),
  ''
].join('\n');
const zenodo={
  title:c.title,upload_type:'software',
  description:'BrainRosetta is a browser-based brain atlas explorer with hierarchical parcellations, template-aware coordinate lookup, and NIfTI ROI mask export. All processing runs locally in the browser. Third-party atlases and libraries retain their own licenses and citation requirements.',
  creators:c.authors.map(a=>({name:`${a['family-names']}, ${a['given-names']}`,...(a.orcid?{orcid:a.orcid.replace('https://orcid.org/','')}: {})})),
  license:c.license.toLowerCase(),access_right:'open',
  keywords:['neuroimaging','brain atlas','parcellation','MRI','NIfTI'],
  related_identifiers:[{identifier:c['repository-code'],relation:'isSupplementTo',scheme:'url'},{identifier:c.url,relation:'isDocumentedBy',scheme:'url'}],
};
// Do not carry a release DOI/version into the next Zenodo archive. Zenodo
// obtains the version from the new GitHub release and assigns a new DOI.
for(const [name,text] of [['CITATION.cff',cff],['.zenodo.json',JSON.stringify(zenodo,null,2)+'\n']]){
  const path=new URL(name,root);
  if(process.argv.includes('--check')){
    if(readFileSync(path,'utf8')!==text)throw new Error(`${name} is stale; run node scripts/prepare_citation.mjs`);
  }else writeFileSync(path,text);
}
